// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJidYjS34pHwsRXesoOZBdGqCBJEr_xCQ',
    appId: '1:922574722443:web:e0da48c2f175fc37164b8e',
    messagingSenderId: '922574722443',
    projectId: 'flutterdemo-11abe',
    authDomain: 'flutterdemo-11abe.firebaseapp.com',
    storageBucket: 'flutterdemo-11abe.appspot.com',
    measurementId: 'G-J7VTS1WHEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf7Bc5W3rFPxoaKrjVExRcMuisRumUTdk',
    appId: '1:922574722443:android:2bf8275f46899250164b8e',
    messagingSenderId: '922574722443',
    projectId: 'flutterdemo-11abe',
    storageBucket: 'flutterdemo-11abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2VMzTuyQVlTrA-PNzOS4249U5zyCUhgY',
    appId: '1:922574722443:ios:62a1ef849550d8d9164b8e',
    messagingSenderId: '922574722443',
    projectId: 'flutterdemo-11abe',
    storageBucket: 'flutterdemo-11abe.appspot.com',
    iosClientId: '922574722443-tarl1b6mp4vq2mqoq9kc7jb4uft9ea2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2VMzTuyQVlTrA-PNzOS4249U5zyCUhgY',
    appId: '1:922574722443:ios:4bf59611394c5774164b8e',
    messagingSenderId: '922574722443',
    projectId: 'flutterdemo-11abe',
    storageBucket: 'flutterdemo-11abe.appspot.com',
    iosClientId: '922574722443-b815036djs02985s7f035f4lkkp51iif.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo.RunnerTests',
  );
}
